### PR TITLE
Major changes in code structure

### PR DESCRIPTION
**Pull request by tuhuynh27**
Refactor due to a lot of unused and duplicate code

### CODE REVIEW

**Review by axblueblader — APPROVED** [review]
Wao great work

**Review by yampml — APPROVED** [review]
Sugee

**Comment by taivtse** [comment]
Just a question @tuhuynh27 . Why does the String package not have a Base class while others do?

**Comment by tuhuynh27** [comment]
Hi @taivtse, the purpose of the "Base Class" is to share some logic between the commands in one package (one category)

For example, https://github.com/keva-dev/keva/blob/dbaafd9cadae87f2f77f4770f201c9c297d32e5c/core/src/main/java/dev/keva/core/command/impl/hash/HashBase.java#L28-L34

This method is re-used many times in other hash commands.

**Comment by taivtse** [comment]
I'm wondering if we have base classes, it seems that the command classes are quite redundant, they just call the methods in the base classes.
Have you considered that we have one class for each command group, and put the @CommandImpl on command methods?

**Comment by tuhuynh27** [comment]
```
Have you considered that we have one class for each command group, and put the @CommandImpl on command methods?
```

@taivtse Sure it's possible to do so, but "one class for each command group" maybe too much code, why not keep them in small classes

**Comment by tuhuynh27** [comment]
This change is also for the next step in Keva storage: **to implement various backend storage support: LevelDB, LMDB, RocksDB, BoltDB, etc.**

I've simplified the Database interface, now the Database implementation can be as simple as:
https://github.com/keva-dev/keva/blob/develop/store/src/main/java/dev/keva/store/impl/ChronicleMapDatabaseImpl.java

It's now easier to write LevelDBImpl.java or BoltDBImpl.java, all of the logic was moved to the `core` package.

cc @yampml @axblueblader @haphananhtuan

**Pull request merged**
