### PR TITLE
Remove spin lock

### LINKED ISSUE #112: Remove spin lock class
As JDK implementation already has spin -> yield -> block lock, we don't need that SpinLock.class anymore, thus removing it.

### PR DESCRIPTION
**Pull request by tuhuynh27**
Resolve #112

### CODE REVIEW

**Comment by yampml** [comment]
問題ない, but what about the read/write lock implementation discussed before?

**Review by yampml — APPROVED** [review]
lgtm

**Comment by tuhuynh27** [comment]
@yampml It will be in another pull request

**Review by axblueblader — APPROVED** [review]
lgtm

**Pull request merged**
