### PR TITLE
Implements Netty Thread-local object pool for Command

### LINKED ISSUE #69: Implement ByteArray pool allocator
Issue: There is a lot of `byte[]` allocated when handling TCP messages:

image

It's better to have a ByteArray pool allocator so that `byte[]` can be reused and avoid creating massive garbage for the GC.

For example:

```java
ByteArrayPoolAllocator pool = ByteArrayPoolAllocator.DEFAULT
byte[10] obj = byteArrayPool.getByteArray(10);
```

### PR DESCRIPTION
**Pull request by tuhuynh27**
`Command` now will be reused, fixes #69

### CODE REVIEW

**Comment by tuhuynh27** [comment]
https://stackoverflow.com/questions/10624232/performance-penalty-of-string-intern

**Review by yampml — APPROVED** [review]
Okay

**Comment by axblueblader** [comment]
> https://stackoverflow.com/questions/10624232/performance-penalty-of-string-intern

From the post answers, looks like it degrades heavily when the number of distinct string increase, can u explain a bit why we should use it?  All the parameter/argument strings are very likely to be distinct.

**Comment by tuhuynh27** [comment]
Sure @axblueblader, like what you said, I'm considering to revert to commit, not to use `.intern()`

**Comment by tuhuynh27** [comment]
Regarding the Object Pool, we will release the object right after done processing Command, for AOF mode, will release after the command is flushed to disk (batches)

**Pull request merged**
