### PR TITLE
Fix unit tests failed - failed to create socket consistently

### LINKED ISSUE #122: Unit tests failed -  Failed to create socket consistently
Building with tests `./gradlew :app:build --parallel` or `./gradlew :app:build` inconsistently cause following errors

```
> Task :core:test
dev.keva.core.server.PersistenceTest save() FAILED (12.1s)

  org.opentest4j.AssertionFailedError
      at dev.keva.core.server.PersistenceTest.sync(PersistenceTest.java:68)
  Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.
      at dev.keva.core.server.PersistenceTest.sync(PersistenceTest.java:61)
  Caused by: java.net.ConnectException: Connection refused (Connection refused)
      at dev.keva.core.server.PersistenceTest.sync(PersistenceTest.java:61)

dev.keva.core.server.AOFTest save() FAILED (12.2s)

  org.opentest4j.AssertionFailedError
      at dev.keva.core.server.AOFTest.sync(AOFTest.java:74)
  Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.
      at dev.keva.core.server.AOFTest.sync(AOFTest.java:67)
  Caused by: java.net.ConnectException: Connection refused (Connection refused)
      at dev.keva.core.server.AOFTest.sync(AOFTest.java:67)

dev.keva.core.server.PersistenceTest recover() FAILED (1s)

  org.opentest4j.AssertionFailedError
      at dev.keva.core.server.PersistenceTest.recover(PersistenceTest.java:98)
  Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.
      at dev.keva.core.server.PersistenceTest.recover(PersistenceTest.java:91)
  Caused by: java.net.ConnectException: Connection refused (Connection refused)
      at dev.keva.core.server.PersistenceTest.recover(PersistenceTest.java:91)

dev.keva.core.server.AOFTest recover() FAILED (1s)

  org.opentest4j.AssertionFailedError
      at dev.keva.core.server.AOFTest.recover(AOFTest.java:106)
  Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.
      at dev.keva.core.server.AOFTest.recover(AOFTest.java:99)
  Caused by: java.net.ConnectException: Connection refused (Connection refused)
      at dev.keva.core.server.AOFTest.recover(AOFTest.java:99)

```

### PR DESCRIPTION
**Pull request by TuanHungVU1202**
Fix #122 Increase timeout for sever to successfully run before running actual tests.

### CODE REVIEW

**Comment by tuhuynh27** [comment]
@axblueblader seems like we've faced similar issue before, can you check on this?

**Comment by TuanHungVU1202** [comment]
> @axblueblader seems like we've faced similar issue before, can you check on this?

@tuhuynh27 I just noticed the build on Github took 1m50s, which is similar to my local pc building with --info. 

Build without logging decreases it to less than 1m. But I'll check the approach suggested in #122 by @axblueblader. There definitely more tests starting the server and time will increase fast even it's quite a "constant".

**Comment by tuhuynh27** [comment]
@TuanHungVU1202 @axblueblader We can utilize `CompletableFuture`:

```java
CompletableFuture<Void> future = server.start();
// Wait until the server is ready.
future.join();
```

**Comment by tuhuynh27** [comment]
Hi @TuanHungVU1202, I will close this PR now, we can have more discussion on #122 and maybe have another PR

**Pull request closed without merging**
